global:
  scrape_interval: 2s
  evaluation_interval: 2s

alerting:
  alertmanagers:
    - static_configs:
        - targets: [ "alertmanager:9093" ]
rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'Prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]

  - job_name: "Demo-Monitoring"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:8082" ]
        labels:
          application: "Demo-Monitoring"

  - job_name: "NodeExporter"
    static_configs:
      - targets: [ "node-exporter:9100" ]

  - job_name: "Postgres Exporter"
    static_configs:
      - targets: [ "postgres-exporter:9187" ]